version: 2.1
jobs:
  build:
    docker:
      - image: "circleci/node:latest"
    steps:
      - checkout
      - run:
          name: install
          command: npm install
      - run:
          name: lint
          command: npm run lint
      - run:
          name: build
          command: npm run build
      - run:
          name: unit-test
          command: npm run test:coverage
      - run:
          name: integration-test
          command: npm run test:integration
      - sonarcloud/scan
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud